import os
import re
import time
import urllib.error
import astropy.units as u
from astropy.time import Time
from sunpy.net import Fido
from sunpy.net import attrs as a

def normalize_hmi_filename(filename):
    """
    Normalize HMI filename by removing numeric suffix (.1/.3/.n) before .magnetogram.fits
    Example:
    - Input: hmi.m_720s.20160120_230000_TAI.1.magnetogram.fits
    - Output: hmi.m_720s.20160120_230000_TAI.magnetogram.fits
    """
    if filename.startswith('hmi.m_720s.') and filename.endswith('.magnetogram.fits'):
        pattern = r'\.(\d+)\.magnetogram\.fits$'
        normalized_name = re.sub(pattern, '.magnetogram.fits', filename)
        return normalized_name
    return filename

def check_save_fn_status(match_log_path, save_dir, output_log_path):
    """
    Check three conditions for download_match_*.txt and save_dir:
    1. Save_fn (2nd column) does not exist in save_dir (ignore .1/.3 suffix)
    2. Duplicate save_fn entries (non-empty) in match log
    3. Files exist in save_dir but not recorded in match log (ignore .1/.3 suffix)
    Output all three types of records to single log file
    Return: missing_save_fns (list), extra_files (list) for follow-up operations
    """
    # Initialize variables
    skip_header = True
    missing_lines = []       # Store (line_num, line) for missing save_fn
    save_fn_records = {}     # Key: save_fn, Value: list of (line_num, line)
    duplicate_lines = []     # Store (line_num, line) for duplicate save_fn
    match_log_save_fns = set()  # All normalized save_fn (non-empty) from match log
    extra_files = []  # Files in save_dir not in match_log_save_fns (original filenames)
    dir_normalized_to_original = {}  # Map normalized name to original filename in save_dir
    missing_save_fns = []    # Missing HMI filenames (original from log) for re-download

    # Preprocess save_dir files: normalize HMI filenames
    for file_name in os.listdir(save_dir):
        file_path = os.path.join(save_dir, file_name)
        if os.path.isfile(file_path) and file_name.startswith('hmi.m_720s.') and file_name.endswith('.fits'):
            normalized_name = normalize_hmi_filename(file_name)
            dir_normalized_to_original[normalized_name] = file_name

    # Step 1: Parse match log and collect data
    with open(match_log_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line_stripped = line.strip()
            if not line_stripped:
                continue

            # Skip header lines
            if skip_header:
                if '-' * 80 in line_stripped or '-' * 120 in line_stripped:
                    skip_header = False
                continue

            # Split line content
            parts = line_stripped.split('|')
            if len(parts) < 2:
                continue

            save_fn = parts[1].strip()
            # Process non-empty save_fn only
            if save_fn and save_fn != '':
                # Normalize save_fn for matching (keep original for duplicate check/log)
                normalized_save_fn = normalize_hmi_filename(save_fn)
                match_log_save_fns.add(normalized_save_fn)
                
                # Check if normalized save_fn exists in save_dir
                if normalized_save_fn not in dir_normalized_to_original:
                    missing_lines.append((line_num, line_stripped))
                    missing_save_fns.append(save_fn)  # Collect missing filenames

                # Record original save_fn for duplicate check
                if save_fn not in save_fn_records:
                    save_fn_records[save_fn] = []
                save_fn_records[save_fn].append((line_num, line_stripped))

    # Step 2: Identify duplicate save_fn entries (based on original name)
    for save_fn, records in save_fn_records.items():
        if len(records) > 1:
            for line_num, line in records:
                duplicate_lines.append((line_num, line))

    # Step 3: Find extra files in save_dir (normalized comparison)
    for normalized_name, original_name in dir_normalized_to_original.items():
        if normalized_name not in match_log_save_fns:
            extra_files.append(original_name)

    # Step 4: Write combined results to output log
    with open(output_log_path, 'w', encoding='utf-8') as f:
        # Write log header
        year = os.path.basename(match_log_path).split('_')[2].split('.')[0]
        f.write(f"===== Save_fn Status Log ({year}) =====\n")
        f.write("Generated by: " + os.path.basename(__file__) + "\n")
        f.write("Check Time: " + str(os.path.getctime(output_log_path)) + "\n")
        f.write("Note: Ignored .1/.3/.n numeric suffix in HMI filenames for matching\n")
        f.write("-" * 150 + "\n")

        # Write missing save_fn section
        f.write("\n[1] MISSING SAVE_FN (not exist in save_dir)\n")
        f.write("Format: Line Number | Full Line Content\n")
        f.write("-" * 150 + "\n")
        if missing_lines:
            for line_num, line in missing_lines:
                f.write(f"{line_num:>4d} | {line}\n")
        else:
            f.write("No missing save_fn entries found\n")

        # Write duplicate save_fn section
        f.write("\n[2] DUPLICATE SAVE_FN (non-empty entries)\n")
        f.write("Format: Line Number | Full Line Content\n")
        f.write("-" * 150 + "\n")
        if duplicate_lines:
            for line_num, line in duplicate_lines:
                f.write(f"{line_num:>4d} | {line}\n")
        else:
            f.write("No duplicate save_fn entries found\n")

        # Write extra files in save_dir section
        f.write("\n[3] EXTRA FILES IN SAVE_DIR (not recorded in match log)\n")
        f.write("Format: Filename\n")
        f.write("-" * 150 + "\n")
        if extra_files:
            for file_name in extra_files:
                f.write(f"{file_name}\n")
        else:
            f.write("No extra files found in save_dir\n")

    # Step 5: Print console summary
    print(f"===== Save_fn Status Check Result =====")
    print(f"Source match log: {match_log_path}")
    print(f"Output log: {output_log_path}")
    print(f"Note: Ignored .1/.3/.n numeric suffix in HMI filenames for matching")
    print(f"\n1. Missing save_fn entries: {len(missing_lines)}")
    print(f"2. Duplicate save_fn entries: {len(duplicate_lines)}")
    print(f"3. Extra files in save_dir: {len(extra_files)}")
    print("\n===== Check Completed =====")

    return missing_save_fns, extra_files

def delete_extra_files(save_dir, extra_files, confirm=True):
    """Delete extra files in save_dir (with confirmation prompt)"""
    if not extra_files:
        print("No extra files to delete.")
        return

    print(f"\n===== Extra Files to Delete ({len(extra_files)}) =====")
    for idx, file in enumerate(extra_files, 1):
        print(f"{idx}. {file}")

    # Confirm deletion
    if confirm:
        response = input("\nConfirm delete these files? (y/n): ").strip().lower()
        if response != 'y':
            print("Deletion cancelled.")
            return

    # Execute deletion
    deleted_count = 0
    for file_name in extra_files:
        file_path = os.path.join(save_dir, file_name)
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"Deleted: {file_path}")
                deleted_count += 1
            else:
                print(f"File not found (skip): {file_path}")
        except Exception as e:
            print(f"Failed to delete {file_path}: {str(e)}")

    print(f"\nDeleted {deleted_count}/{len(extra_files)} extra files.")

if __name__ == '__main__':
    # Configuration
    year_record = '2011'
    save_dir_root = 'E:/Research/Data/SDO/HMI/FullDisk/Magnetogram/4096/'
    jsoc_email = 'ruizhuo@pku.edu.cn'  # Replace with your JSOC email
    delete_extra = True  # Set to False to skip deletion
    redownload_missing = False  # Set to True to enable re-download

    # Derived paths
    save_dir = os.path.join(save_dir_root, year_record)
    match_log_path = os.path.join(save_dir_root, f'download_match_{year_record}.txt')
    output_log_path = os.path.join(save_dir_root, f'download_check_{year_record}.txt')

    # Step 1: Validate input
    if not os.path.exists(match_log_path):
        print(f"Error: Match log file {match_log_path} does not exist!")
        exit(1)
    if not os.path.exists(save_dir):
        print(f"Error: Save directory {save_dir} does not exist!")
        exit(1)

    # Step 2: Run save_fn check (returns missing/extra files directly)
    missing_save_fns, extra_files = check_save_fn_status(match_log_path, save_dir, output_log_path)

    # Step 3: Delete extra files (optional)
    if delete_extra:
        delete_extra_files(save_dir, extra_files, confirm=True)

    print("\n===== All Operations Completed =====")