seed: 42
batch_size: 6
learning_rate: 0.0001
epochs: 300
milestones:
- 200
- 400
- 600
- 800
cc_weight: 0.01
model:
  name: lte
  args:
    encoder_spec:
      name: rcan
      args:
        no_upsampling: true
        n_channels: 2
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list:
        - 256
        - 256
        - 256
    hidden_dim: 256
    use_pm: false
